PATH_DICT = "/work/dict"
DICT_FOLDER_IS_NOT_FOUND = """Can not find folder with dicts.Manually create folder 'dict' in your work folder and put there txt files with wordlists"""
WORDLISTS_IS_NOT_FOUND = """Can not find any worldlists in your '$work/dict' folder. Create txt file and put words there separated by new line"""
WORDLISTS_IS_EMPTY = """Please select wordlist to use"""
CORES_ARE_EMPTY = "Please specify number of cores to use"
INDEX_DEPTH_IS_EMPTY = "Please specify index depth"
